---
name: Running Project Unit Tests
description: Runs all project unit tests
on:
  pull_request:
    branches:
      - dev
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: |
        pip uninstall jwt -y
        rm -rf .venv/lib/python3.9/site-packages/jwt
        echo "Running all Unit tests..."
        echo
        source auth-api-3.9/bin/activate
        pytest -v tests/
        echo
        echo "All unit test were run."

      shell: bash
